CREATE DATABASE DB_TESTEPROJECT;

USE DB_TESTEPROJECT;

CREATE TABLE IF NOT EXISTS TB_SEXOS(

SEX_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
SEX_NOME VARCHAR(20) NOT NULL,
SEX_SIGLA CHAR(1) NOT NULL,
CONSTRAINT PRIMARY KEY (SEX_ID)
);

INSERT INTO TB_SEXOS
(SEX_NOME,SEX_SIGLA)
VALUES
('MASCULINO','M'),('FEMININO','F');

CREATE TABLE IF NOT EXISTS TB_UFS(

UF_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
UF_NOME VARCHAR(20) NOT NULL,
UF_SIGLA CHAR(2) NOT NULL,
CONSTRAINT PRIMARY KEY (UF_ID)
);

INSERT INTO TB_UFS
(UF_NOME,UF_SIGLA)
VALUES
('RIO GRANDE DO NORTE','RN');

CREATE TABLE IF NOT EXISTS TB_CIDADES(

CID_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
CID_UF_ID INT UNSIGNED NOT NULL,
CID_NOME VARCHAR(30) NOT NULL,
CONSTRAINT PRIMARY KEY (CID_ID),
CONSTRAINT FK_UF_CID FOREIGN KEY (CID_UF_ID) REFERENCES TB_UFS(UF_ID)
);

INSERT INTO TB_CIDADES
(CID_UF_ID,CID_NOME)
VALUES
(1,'NATAL'),(1,'PARNAMIRIM');

CREATE TABLE IF NOT EXISTS TB_BAIRROS(

BAI_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
BAI_CID_ID INT UNSIGNED NOT NULL,
BAI_NOME VARCHAR(30) NOT NULL,
CONSTRAINT PRIMARY KEY (BAI_ID),
CONSTRAINT FK_CID_BAI FOREIGN KEY (BAI_CID_ID) REFERENCES TB_CIDADES(CID_ID)
);

INSERT INTO TB_BAIRROS
(BAI_CID_ID,BAI_NOME)
VALUES
(1,'CAPIM MACIO'),(1,'CIDADE ALTA'),(2,'NOVA PARNAMIRIM');

CREATE TABLE IF NOT EXISTS TB_CLIENTES(

CLI_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
CLI_NOME VARCHAR(40) NOT NULL,
CLI_SOBRENOME VARCHAR(40) NOT NULL,
CLI_DATA DATE NOT NULL,
CLI_CPF VARCHAR(14) NOT NULL,
CLI_SEX_ID INT UNSIGNED NOT NULL,
CLI_CEP VARCHAR(9) NOT NULL,
CLI_LOGRADOURO VARCHAR(60) NOT NULL,
CLI_OBSERVACOES VARCHAR(50) NOT NULL,
CLI_BAI_ID INT UNSIGNED NOT NULL,
CLI_EMAIL VARCHAR(50) NOT NULL,
CONSTRAINT PRIMARY KEY (CLI_ID),
CONSTRAINT FK_SEX_CLI FOREIGN KEY (CLI_SEX_ID) REFERENCES TB_SEXOS(SEX_ID),
CONSTRAINT FK_BAI_CLI FOREIGN KEY (CLI_BAI_ID) REFERENCES TB_BAIRROS(BAI_ID)
);